In [6]:
import sqlalchemy
import psycopg2
PostgresDB_URI = 'postgres+psycopg2://postgres:admin@localhost:5432/postgres'

In [7]:
from sqlalchemy import create_engine 
engine = create_engine(PostgresDB_URI)
connection = engine.connect() 
connection = connection.execution_options(isolation_level="READ COMMITTED") 

from sqlalchemy.sql import text
MyQuery = text("SELECT * FROM \"Coronavirus\"") 
srinurow = connection.execute(MyQuery).fetchall()

In [8]:
import pandas as pd
import numpy as np

#read the data set
data_df = pd.DataFrame(srinurow)
data_df.columns = ['Country', 'TotalCases', 'NewCases', 'TotalDeaths', 'NewDeaths', 'TotalRecovered', 
                   'ActiveCases', 'SeriousCases', 'TotalCasesPM','DeathsPM', 'TotalTests', 'TestsPM','Population']
data_df

,Country,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,ActiveCases,SeriousCases,TotalCasesPM,DeathsPM,TotalTests,TestsPM,Population
0,USA,16191184,142256,301760,1935,9389300,6500124,27357,48788,909,216479383,652311,331865090
1,India,9826031,29039,142618,396,9321249,362164,8944,7089,103,151632223,109402,1386012075
2,Brazil,6794910,11367,179897,96,5931777,683236,8318,31867,844,25700000,120527,213230064
3,Russia,2597711,28585,45893,613,2059840,491978,2300,17797,314,81564365,558804,145962393
4,France,2351372,13406,57567,412,175891,2117914,2884,35988,881,28508991,436332,65337886
5,UK,1809455,21672,63506,424,0,0,1267,26592,933,47141344,692801,68044545
6,Italy,1805873,18727,63387,761,1052163,690323,3265,29888,1049,23866590,394998,60422081
7,Turkey,1780673,32106,15977,226,1154333,610363,5952,21013,189,20709452,244386,84740585
8,Spain,1741439,7053,47624,280,0,0,2100,37240,1018,24101272,515393,46762862
9,Argentina,1482216,0,40431,0,1318187,123598,3665,32663,891,4173392,91966,45379520
10,Colombia,1399911,0,38484,0,1296420,65007,2376,27383,753,6915466,135271,51122861
11,Germany,1296298,25866,21773,540,942100,332425,4432,15450,260,30494036,363443,83903248
12,Mexico,1217126,11897,112326,671,896130,208670,3515,9396,867,3118237,24073,129532213
13,Poland,1115201,13110,22174,544,815356,277671,1766,29481,586,6620376,175012,37828086
14,Iran,1092407,9384,51727,232,787853,252827,5768,12933,612,6611783,78276,84467718
15,Peru,979111,0,36499,0,914600,28012,1019,29514,1100,5217086,157262,33174480
16,Ukraine,872228,13514,14755,285,480348,377125,177,19998,338,4957299,113658,43615882
17,South Africa,845083,8319,22952,205,758373,63758,546,14170,385,5779544,96909,59638974
18,Indonesia,605243,6310,18511,175,496886,89846,0,2202,67,6271943,22823,274803482
19,Belgium,600397,2754,17692,89,40789,541916,657,51705,1524,6231437,536635,11612063
20,Netherlands,594523,8838,9966,64,0,0,486,34662,581,5077285,296021,17151770
21,Iraq,572600,1347,12549,23,503897,56154,197,14097,309,3837024,94467,40617505
22,Czechia,569205,5864,9341,57,497828,62036,550,53108,872,3294949,307427,10717838
23,Chile,567974,1534,15782,8,541345,10847,663,29599,822,5686946,296366,19188940
24,Romania,545567,6460,13116,168,443168,89283,1299,28444,684,4386813,228717,19180085
25,Bangladesh,487849,1884,6986,19,414318,66545,0,2949,42,2944252,17799,165415819
26,Philippines,447039,1504,8709,8,409329,29001,1401,4056,79,6154475,55836,110224876
27,Canada,446361,4292,13222,113,359921,73218,530,11781,349,12317829,325105,37888820
28,Pakistan,432327,3047,8653,50,379092,44582,2538,1941,39,5948742,26703,222774877
29,Morocco,394564,3035,6542,50,349821,38201,982,10634,176,4161069,112146,37103931
...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Barbados,291,0,7,0,269,15,1,1012,24,52152,181378,287532
191,Saint Lucia,274,3,4,1,186,84,0,1489,22,17231,93647,184000
192,Seychelles,187,3,0,0,182,5,0,1896,0,5200,52729,98617
193,Caribbean Netherlands,172,0,3,0,160,9,0,6532,114,3873,147089,26331
194,St Barth,162,0,1,0,127,34,0,16380,101,5315,537412,9890
195,Brunei,152,0,3,0,147,2,0,346,7,77829,177152,439334
196,Antigua and Barbuda,147,1,4,0,138,5,2,1496,41,5126,52152,98289
197,St Vincent Grenadines,94,3,0,0,81,13,0,846,0,11720,105493,111097
198,Dominica,87,2,0,0,76,11,0,1207,0,6175,85685,72066
199,British Virgin Islands,75,0,1,0,72,2,0,2474,33,8846,291755,30320
200,Macao,46,0,0,0,46,0,0,70,0,4238,6488,653241
201,Fiji,44,0,2,0,35,7,0,49,2,17576,19543,899328
202,Grenada,43,0,0,0,41,2,0,381,0,6252,55448,112755
203,Laos,41,0,0,0,33,8,0,6,0,83753,11438,7322111
204,New Caledonia,36,0,0,0,32,4,0,126,0,18012,62822,286714
205,Timor-Leste,31,0,0,0,30,1,0,23,0,14932,11232,1329471
206,Vatican City,27,0,0,0,15,12,0,33666,0,0,0,802
207,Saint Kitts and Nevis,26,0,0,0,23,3,0,487,0,4358,81662,53366
208,Greenland,19,0,0,0,18,1,0,334,0,13742,241877,56814
209,Falkland Islands,17,0,0,0,17,0,0,4824,0,4746,1346765,3524
210,Solomon Islands,17,0,0,0,5,12,0,24,0,4500,6482,694241
211,Saint Pierre Miquelon,14,0,0,0,14,0,0,2422,0,2946,509600,5781
212,Montserrat,13,0,1,0,12,0,0,2604,200,626,125376,4993
213,Western Sahara,10,0,1,0,8,1,0,17,2,0,0,603753
214,Anguilla,10,0,0,0,3,7,0,664,0,2651,176006,15062
215,MS Zaandam,9,0,2,0,7,0,0,0,0,0,0,0
216,Marshall Islands,4,0,0,0,4,0,0,67,0,0,0,59367
217,Wallis and Futuna,3,0,0,0,1,2,0,269,0,1149,103049,11150
218,Samoa,2,0,0,0,2,0,0,10,0,0,0,198999
219,Vanuatu,1,0,0,0,1,0,0,3,0,0,0,310283

In [15]:
data_df = pd.DataFrame(['SeriousCases','NewCases'])['Population'].sum().reset_index()
data_df

KeyError: 'Population'